### ISSUE TITLE
Linux Foundation move and project rename: news post 404

### ISSUE THREAD

**Issue by draeath** [apptainer/apptainer.org#44]
Various sites still try to point at [this news URL](https://apptainer.org/news/community-announcement-20211130) which is now 404. This includes the [migration page](https://apptainer.org/docs/admin/main/singularity_migration.html).

That page should be recreated, replaced with a redirect to an appropriate location, or the referencing docs (where possible) should be edited.

Apologies if this is not the correct repository to file this issue on.

**Comment by draeath** [comment]
[The original page, a few days after initial publication, per the internet archive.](https://web.archive.org/web/20211217195916/https://apptainer.org/news/community-announcement-20211130/)

**Comment by DrDaveD** [comment]
This is the right place, thanks for the report.

Right, the announcement is still hosted but the name has changed to have  hyphens.  https://apptainer.org/news/community-announcement-2021-11-30/.  @ressonix please fix.

**Comment by ressonix** [comment]
I have pushed a change to correct this. I'm not sure how the hyphens happened, I just copied over the markdown files from the original.

Should be deploying within 10 minutes.

**Comment by draeath** [comment]
Looks good from here! Wow, that was fast :)
